version: '3.8'
services:
  postgres:
    container_name: pgserver
    # the bullseye version is a light weight version
    image: postgres:14.2-bullseye
    # the environment values are in the .env file
    # this is for local development only
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
    # maps the local and container ports
      - "5432:5432"
    restart: always
    volumes:
    # a docker volume is a shared space between
    # the local computer and the container
    # so data can be shared and persist
      - ./db-data:/var/lib/postgresql/data 
      - ./sql/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
      # The db-data folder is copied in the working directory
      # of our computer so our data is persistent
      # If needing to rebuild the DB completely, delete the
      # db-data folder first, then rebuild
    # meant to solve an error with postgres statistics
    command: postgres -c stats_temp_directory=/tmp

  app:
    container_name: nodeserver
    build: .
    depends_on:
      # Our app does not work without our database
      # so this ensures the database loads first
      - postgres
    # maps the local port to the container port
    ports:
      - "5500:5500"
    volumes:
      # Maps our current project directory `.` to
      # our working directory in the container (/app)
      - ./:/app
      # node_modules workaround for volumes
      # https://stackoverflow.com/a/32785014
      - /app/node_modules    
        